Запускать нужно файл test_main.py

При запуске можете заметить, что данные которые прилетают с ардуино не постоянные. Я считаю, что нужно проверить либо датчик, либо код ардуино. 
Вывод примерно следующий. 
2023-05-07 22:57:00.844 | INFO     | __main__:main:26 - ultrasonic distance sleep 0.1: 250      - считывание через 0,1 сек
2023-05-07 22:57:00.846 | INFO     | __main__:main:27 - ultrasonic distance sleep 0.1 - type float: 250.0 - конвертирование в float
2023-05-07 22:57:01.848 | INFO     | __main__:main:30 - ultrasonic distance sleep 1: 4741       - считывание через 1 сек, след вывод такая же логика
2023-05-07 22:57:01.850 | INFO     | __main__:main:31 - ultrasonic distance sleep 1 - type float: 4741.0
2023-05-07 22:57:03.851 | INFO     | __main__:main:34 - ultrasonic distance sleep 2: 433
2023-05-07 22:57:03.852 | INFO     | __main__:main:35 - ultrasonic distance sleep 2 - type float: 433.0
2023-05-07 22:57:07.857 | INFO     | __main__:main:38 - ultrasonic distance sleep 4: 192
2023-05-07 22:57:07.858 | INFO     | __main__:main:39 - ultrasonic distance sleep 4 - type float: 192.0


Вам нужно нормализовать работу датчика расстояния. Как я понимаю по выводу, ошибки в считывании особой нет. Ошибочно передается расстояние. 
Также проверьте, что случается при появлении коровы. Если расстояние нормально меньше 40, то ничего менять не нужно. 